<Button>:
    font_size: 40
    color: 0,1,0,1

<Widgets>:
    Button:
        size: 100,75
        pos: root.x, root.top - self.height
        text: "Kivy"
        color: 0,1,0,1

    Button:
        size: 300,75
        pos: 100,0
        text: "2kome Botan"
        color: 1,0,0,1

<FloatLayout>:
    Button:
        text: "button 1"
        size_hint: 0.3, 0.2
        pos_hint: {"x":0, "top":1}
